### ISSUE TITLE
Not all python package versions uploaded

### ISSUE THREAD

**Issue by jgoppert** [conda-forge/px4tools-feedstock#2]
@jakirkham  Any idea what is going on here. My packages aren't labelled with a python version and seem to be randomly 2.7 or 3.4. It is like I somehow managed to label the package name incorrectly and it is overwriting.

https://anaconda.org/conda-forge/px4tools/files

**Comment by pelson** [comment]
Looks like you have missed the _python_ run time dependency. Even though some of your dependencies depend on python, if you don't _explicitly_ state the dependency on python, conda-build doesn't add the `pyXX` version as a build string, and you end up with the overwriting conflict you are seeing (and a package that doesn't express it's python version pinning).

**Comment by jgoppert** [comment]
@pelson Thanks!
